name: build
on:
 push:
  paths:
   - '**.js'
jobs:
 build:
  name: my job
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [ubuntu-latest]
    node: [12, 14]
  steps:
   - name: my first step
     env:
      MY_VAR: Hi there! my name is
      FIRST_NAME: Renato
      MIDDLE_NAME: Lagares
      LAST_NAME: Marcandier Goncalves
     run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
