name: test

on:
 pull_request:
  branches:
  - master
jobs:
 build:
  name: my job
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    node: [12]
    os: [macos-latest, windows-latest, ubuntu-latest]
    
    include:
     - node: 13
       os: ubuntu-18.04
       experimental: true
  steps:
    - uses: actions/checkout@v2
    - name: Use node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm test
    
